### ISSUE TITLE
Service account credentials aren't localized to preemptible workers

### ISSUE THREAD

**Issue by rtitle** [DataBiosphere/leonardo#127]
Original JIRA: https://broadinstitute.atlassian.net/browse/GAWB-2921

Alisa tried doing this and HAIL barfed the scary barf at her below.

I ssh'd onto the preemptible VM and there was nothing sitting at /etc/service-account-credentials.json. There was on non-preemptible worker nodes.

```
FatalErrorTraceback (most recent call last)
<ipython-input-10-d61abe05c47a> in <module>()
----> 1 vds.summarize().report()

<decorator-gen-553> in summarize(self)

/hail/hail-0.1-6f8598516c88.zip/hail/java.pyc in handle_py4j(func, *args, **kwargs)
    119         raise FatalError('%s\n\nJava stack trace:\n%s\n'
    120                          'Hail version: %s\n'
--> 121                          'Error summary: %s' % (deepest, full, Env.hc().version, deepest))
    122     except py4j.protocol.Py4JError as e:
    123         if e.args[0].startswith('An error occurred while calling'):

FatalError: FileNotFoundException: /etc/service-account-credentials.json (No such file or directory)
It is possible the underlying files have been updated. You can explicitly invalidate the cache in Spark by running 'REFRESH TABLE tableName' command in SQL or by recreating the Dataset/DataFrame involved.

Java stack trace:
org.apache.spark.SparkException: Job aborted due to stage failure: Task 51 in stage 5.0 failed 4 times, most recent failure: Lost task 51.3 in stage 5.0 (TID 2707, sampleqc-pca-sw-f2p0.c.topmed-shared.internal): java.io.FileNotFoundException: /etc/service-account-credentials.json (No such file or directory)
It is possible the underlying files have been updated. You can explicitly invalidate the cache in Spark by running 'REFRESH TABLE tableName' command in SQL or by recreating the Dataset/DataFrame involved.
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:119)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:91)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:370)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at is.hail.sparkextras.OrderedRDD$$anonfun$apply$8$$anon$2.hasNext(OrderedRDD.scala:199)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at is.hail.sparkextras.OrderedRDD$$anonfun$apply$8$$anon$2.hasNext(OrderedRDD.scala:199)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at is.hail.sparkextras.OrderedRDD$$anonfun$apply$8$$anon$2.foreach(OrderedRDD.scala:195)
	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
	at is.hail.sparkextras.OrderedRDD$$anonfun$apply$8$$anon$2.foldLeft(OrderedRDD.scala:195)
	at scala.collection.TraversableOnce$class.aggregate(TraversableOnce.scala:214)
	at is.hail.sparkextras.OrderedRDD$$anonfun$apply$8$$anon$2.aggregate(OrderedRDD.scala:195)
	at org.apache.spark.rdd.RDD$$anonfun$aggregate$1$$anonfun$22.apply(RDD.scala:1089)
	at org.apache.spark.rdd.RDD$$anonfun$aggregate$1$$anonfun$22.apply(RDD.scala:1089)
	at org.apache.spark.SparkContext$$anonfun$32.apply(SparkContext.scala:1935)
	at org.apache.spark.SparkContext$$anonfun$32.apply(SparkContext.scala:1935)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
	at org.apache.spark.scheduler.Task.run(Task.scala:86)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1454)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1442)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1441)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1441)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:811)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:811)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:811)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1667)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1622)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1611)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:632)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1873)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1936)
	at org.apache.spark.rdd.RDD$$anonfun$aggregate$1.apply(RDD.scala:1091)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:358)
	at org.apache.spark.rdd.RDD.aggregate(RDD.scala:1084)
	at is.hail.variant.VariantDatasetFunctions$.summarize$extension(VariantDataset.scala:220)
	at is.hail.variant.VariantDatasetFunctions.summarize(VariantDataset.scala:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:237)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)java.io.FileNotFoundException: /etc/service-account-credentials.json (No such file or directory)
It is possible the underlying files have been updated. You can explicitly invalidate the cache in Spark by running 'REFRESH TABLE tableName' command in SQL or by recreating the Dataset/DataFrame involved.
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:119)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:91)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:370)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at is.hail.sparkextras.OrderedRDD$$anonfun$apply$8$$anon$2.hasNext(OrderedRDD.scala:199)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at is.hail.sparkextras.OrderedRDD$$anonfun$apply$8$$anon$2.hasNext(OrderedRDD.scala:199)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at is.hail.sparkextras.OrderedRDD$$anonfun$apply$8$$anon$2.foreach(OrderedRDD.scala:195)
	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
	at is.hail.sparkextras.OrderedRDD$$anonfun$apply$8$$anon$2.foldLeft(OrderedRDD.scala:195)
	at scala.collection.TraversableOnce$class.aggregate(TraversableOnce.scala:214)
	at is.hail.sparkextras.OrderedRDD$$anonfun$apply$8$$anon$2.aggregate(OrderedRDD.scala:195)
	at org.apache.spark.rdd.RDD$$anonfun$aggregate$1$$anonfun$22.apply(RDD.scala:1089)
	at org.apache.spark.rdd.RDD$$anonfun$aggregate$1$$anonfun$22.apply(RDD.scala:1089)
	at org.apache.spark.SparkContext$$anonfun$32.apply(SparkContext.scala:1935)
	at org.apache.spark.SparkContext$$anonfun$32.apply(SparkContext.scala:1935)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
	at org.apache.spark.scheduler.Task.run(Task.scala:86)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)


Hail version: 0.1-6f85985
Error summary: FileNotFoundException: /etc/service-account-credentials.json (No such file or directory)
It is possible the underlying files have been updated. You can explicitly invalidate the cache in Spark by running 'REFRESH TABLE tableName' command in SQL or by recreating the Dataset/DataFrame involved.
```

**Comment by rtitle** [comment]
Some things have changed since this was reported, most notably pets-per-project. We should re-test and see if this is still the case. Note we should make sure this works in both cluster-service-account mode and notebook-service-account mode.

**Comment by rtitle** [comment]
Add part of this, create auto tests that create clusters with preemptible workers.
