### ISSUE TITLE
liquibase failing on leonardo init; "Invalid default value for createdDate"

### ISSUE THREAD

**Issue by eap** [DataBiosphere/leonardo#191]
I'm trying to initialize a new Leo server + database. I've created an configured mysql and added an empty 'leonardo' database. When I start Leonardo I get the following trace that seems to be related to CLUSTER.createdDate.

Any idea what's going on here?

```
INFO 2/11/18 7:18 AM: liquibase: Successfully acquired change log lock
INFO 2/11/18 7:18 AM: liquibase: Creating database history table with name: leonardo.DATABASECHANGELOG
INFO 2/11/18 7:18 AM: liquibase: Reading from leonardo.DATABASECHANGELOG
INFO 2/11/18 7:18 AM: liquibase: org/broadinstitute/dsde/workbench/leonardo/liquibase/changelog.xml: leonardo::cluster::thibault: Table CLUSTER created
INFO 2/11/18 7:18 AM: liquibase: org/broadinstitute/dsde/workbench/leonardo/liquibase/changelog.xml: leonardo::cluster::thibault: ChangeSet leonardo::cluster::thibault ran successfully in 24ms
INFO 2/11/18 7:18 AM: liquibase: org/broadinstitute/dsde/workbench/leonardo/liquibase/changelog.xml: leonardo::label::thibault: Table LABEL created
INFO 2/11/18 7:18 AM: liquibase: org/broadinstitute/dsde/workbench/leonardo/liquibase/changelog.xml: leonardo::label::thibault: Index FK_CLUSTER_ID created
INFO 2/11/18 7:18 AM: liquibase: org/broadinstitute/dsde/workbench/leonardo/liquibase/changelog.xml: leonardo::label::thibault: Foreign key constraint added to LABEL (clusterId)
INFO 2/11/18 7:18 AM: liquibase: org/broadinstitute/dsde/workbench/leonardo/liquibase/changelog.xml: leonardo::label::thibault: Unique constraint added to LABEL(clusterId, key)
INFO 2/11/18 7:18 AM: liquibase: org/broadinstitute/dsde/workbench/leonardo/liquibase/changelog.xml: leonardo::label::thibault: ChangeSet leonardo::label::thibault ran successfully in 188ms
INFO 2/11/18 7:18 AM: liquibase: org/broadinstitute/dsde/workbench/leonardo/liquibase/changelog.xml: leonardo::cluster-unique-key::thibault: Unique constraint added to CLUSTER(googleProject, clusterName)
INFO 2/11/18 7:18 AM: liquibase: org/broadinstitute/dsde/workbench/leonardo/liquibase/changelog.xml: leonardo::cluster-unique-key::thibault: ChangeSet leonardo::cluster-unique-key::thibault ran successfully in 18ms
INFO 2/11/18 7:18 AM: liquibase: org/broadinstitute/dsde/workbench/leonardo/liquibase/changelog.xml: leonardo::cluster-googleId-unique-key::thibault: Unique constraint added to CLUSTER(googleId)
INFO 2/11/18 7:18 AM: liquibase: org/broadinstitute/dsde/workbench/leonardo/liquibase/changelog.xml: leonardo::cluster-googleId-unique-key::thibault: ChangeSet leonardo::cluster-googleId-unique-key::thibault ran successfully in 16ms
SEVERE 2/11/18 7:18 AM: liquibase: org/broadinstitute/dsde/workbench/leonardo/liquibase/changelog.xml: leonardo::cluster-createdDate-default::kumra: Change Set leonardo::cluster-createdDate-default::kumra failed.  Error: Invalid default value for 'createdDate' [Failed SQL: ALTER TABLE  CLUSTER
            CHANGE createdDate createdDate TIMESTAMP(6) NOT NULL DEFAULT 0]
INFO 2/11/18 7:18 AM: liquibase: leonardo::cluster-createdDate-default::kumra: Successfully released change log lock
Exception in thread "main" liquibase.exception.MigrationFailedException: Migration failed for change set leonardo::cluster-createdDate-default::kumra:
     Reason: liquibase.exception.DatabaseException: Invalid default value for 'createdDate' [Failed SQL: ALTER TABLE  CLUSTER
            CHANGE createdDate createdDate TIMESTAMP(6) NOT NULL DEFAULT 0]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:619)
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:51)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:79)
	at liquibase.Liquibase.update(Liquibase.java:214)
	at liquibase.Liquibase.update(Liquibase.java:192)
	at liquibase.Liquibase.update(Liquibase.java:188)
	at org.broadinstitute.dsde.workbench.leonardo.db.DbReference$.initWithLiquibase(DbReference.scala:30)
	at org.broadinstitute.dsde.workbench.leonardo.db.DbReference$.init(DbReference.scala:53)
	at org.broadinstitute.dsde.workbench.leonardo.Boot$.startup(Boot.scala:66)
	at org.broadinstitute.dsde.workbench.leonardo.Boot$.delayedEndpoint$org$broadinstitute$dsde$workbench$leonardo$Boot$1(Boot.scala:108)
	at org.broadinstitute.dsde.workbench.leonardo.Boot$delayedInit$body.apply(Boot.scala:26)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at org.broadinstitute.dsde.workbench.leonardo.Boot$.main(Boot.scala:26)
	at org.broadinstitute.dsde.workbench.leonardo.Boot.main(Boot.scala)
Caused by: liquibase.exception.DatabaseException: Invalid default value for 'createdDate' [Failed SQL: ALTER TABLE  CLUSTER
            CHANGE createdDate createdDate TIMESTAMP(6) NOT NULL DEFAULT 0]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:309)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:55)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:113)
	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1277)
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1259)
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:582)
	... 19 more
Caused by: java.sql.SQLSyntaxErrorException: Invalid default value for 'createdDate'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:536)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:513)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:115)
	at com.mysql.cj.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:1983)
	at com.mysql.cj.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:1936)
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:891)
	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:795)
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:95)
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:307)
	... 24 more
```

**Comment by rtitle** [comment]
@eap what MySQL version are you using? We have 5.6 in our enviornment:
```
MySQL [leonardo]> SHOW VARIABLES LIKE "version";
+---------------+-------------------+
| Variable_name | Value             |
+---------------+-------------------+
| version       | 5.6.36-google-log |
+---------------+-------------------+
```
Also I'm wondering if you have strict mode enabled:
```
MySQL [leonardo]> SHOW VARIABLES LIKE 'sql_mode';
+---------------+-------------------+
| Variable_name | Value             |
+---------------+-------------------+
| sql_mode      | STRICT_ALL_TABLES |
+---------------+-------------------+
```

Reading the docs, it looks like 5.7 made the change to make `NO_ZERO_DATE` enabled by default if you're using strict mode. See: https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_no_zero_date

As a workaround, setting sql_mode `ALLOW_INVALID_DATES` might fix it:
https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_allow_invalid_dates. Not sure if you're using Gogole Cloud SQL -- but it looks like there an option in the console to enable it. Otherwise I think there's a serverside conf file somewhere (`/etc/mysql/my.cnf`?)

IIRC we did this because we wanted this column to be part of a unique index but MySQL doesn't play nice with nullable columns in indexes. We can look if there's another solution that doesn't break strictness...

**Comment by eap** [comment]
This was absolutely the case, I just downgraded to 5.6 and I'm not encountering any fatal errors. I have some additional work and tests to do but I should have a few PRs coming this week related to deploy automation and getting this running outside of Firecloud.

**Comment by rtitle** [comment]
OK great. Let us know if you have any questions.

**Comment by davidbernick** [comment]
Hi @eap , can you please share your deploy automation and devops scripts ahead of the pr (what branch ). We are doing work in that’s space and don’t want to duplicate effort.
@hjfbynara @jacmrob

**Comment by eap** [comment]
At the moment I've written it for myself, so there's lots of insecure cruft and some secrets (hence, no push so far). I'll try to clean it up a little and put it out here today or tomorrow.
