### ISSUE TITLE
Intermittent test failure: 403 errors when using preemptibles

### ISSUE THREAD

**Issue by rtitle** [DataBiosphere/leonardo#204]
This test is failing intermittently in dev:

> org.broadinstitute.dsde.workbench.leonardo.ClusterMonitoringSpec.Leonardo clusters should execute Hail with correct permissions on a cluster with preemptible workers

The below links are all dev-deploy test runs on 2/20.

Error happened:
https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-fiab-test-runner/203/
https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-fiab-test-runner/200/

Error did not happen:
https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-fiab-test-runner/202/
https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-fiab-test-runner/197/

Stack trace: 
```
Hail version: 0.1-5c275cc
Error summary: GoogleJsonResponseException: 403 Forbidden
{
  "code" : 403,
  "errors" : [ {
    "domain" : "global",
    "message" : "pet-109021626430559047321@leonardo-billing-spec-e6jcfn0.iam.gserviceaccount.com does not have storage.objects.get access to leo-auto-0c21260d-793a-4108-b0cd-1b3deab534b6/chr20.vcf.",
    "reason" : "forbidden"
  } ],
  "message" : "pet-109021626430559047321@leonardo-billing-spec-e6jcfn0.iam.gserviceaccount.com does not have storage.objects.get access to leo-auto-0c21260d-793a-4108-b0cd-1b3deab534b6/chr20.vcf."
}" did not include substring "Samples: 1092
        Variants: 855026
       Call Rate: 0.983877
         Contigs: ['20']
   Multiallelics: 0
            SNPs: 824953
            MNPs: 0
      Insertions: 12227
       Deletions: 17798
 Complex Alleles: 48
    Star Alleles: 0
     Max Alleles: 2"
      at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
      at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6668)
      at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6704)
      at org.broadinstitute.dsde.workbench.leonardo.LeonardoTestUtils$class.verifyHailImport(LeonardoTestUtils.scala:339)
      at org.broadinstitute.dsde.workbench.leonardo.ClusterMonitoringSpec.verifyHailImport(ClusterMonitoringSpec.scala:10)
      at org.broadinstitute.dsde.workbench.leonardo.ClusterMonitoringSpec$$$$$$cd708838f5b0e01529cb29c62215e4f$$$$fun$4$$anonfun$apply$12.apply(ClusterMonitoringSpec.scala:119)
```

**Comment by rtitle** [comment]
Once this is fixed unignore the test:
https://github.com/DataBiosphere/leonardo/pull/210

**Comment by rtitle** [comment]
Might fix this: https://github.com/DataBiosphere/leonardo/pull/238
