### ISSUE TITLE
Intermittent test failure: failed to delete error'd cluster

### ISSUE THREAD

**Issue by rtitle** [DataBiosphere/leonardo#205]
This test is failing intermittently in dev:
> org.broadinstitute.dsde.workbench.leonardo.ClusterMonitoringSpec.Leonardo clusters should error on cluster create and delete the cluster

The below links are all dev-deploy test runs on 2/20.

Error happened:
https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-fiab-test-runner/197/
https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-fiab-test-runner/202/

Error did not happen:
https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-fiab-test-runner/203/
https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-fiab-test-runner/200/

Stack trace:
```
Error Message
{"statusCode":500,"source":"leonardo","causes":[],"exceptionClass":"org.broadinstitute.dsde.workbench.model.WorkbenchException","stackTrace":[],"message":"Call to Google API failed for leonardo-billing-spec-xgqpqee / automation-test-ahwwewonz. Status: 400. Message: Cannot delete cluster 'automation-test-ahwwewonz' while it has other pending delete operations."}
Stacktrace
      org.broadinstitute.dsde.workbench.service.RestException: {"statusCode":500,"source":"leonardo","causes":[],"exceptionClass":"org.broadinstitute.dsde.workbench.model.WorkbenchException","stackTrace":[],"message":"Call to Google API failed for leonardo-billing-spec-xgqpqee / automation-test-ahwwewonz. Status: 400. Message: Cannot delete cluster 'automation-test-ahwwewonz' while it has other pending delete operations."}
      at org.broadinstitute.dsde.workbench.service.RestClient$class.org$broadinstitute$dsde$workbench$service$RestClient$$throwRestException(RestClient.scala:67)
      at org.broadinstitute.dsde.workbench.service.RestClient$$anonfun$1$$anonfun$apply$1.apply(RestClient.scala:44)
      at org.broadinstitute.dsde.workbench.service.RestClient$$anonfun$1$$anonfun$apply$1.apply(RestClient.scala:39)
      at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
      at scala.util.Try$.apply(Try.scala:192)
      at scala.util.Success.map(Try.scala:237)
      at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
      at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
      at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
      at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
      at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
      at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
      at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
      at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
      at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
      at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
      at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
      at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
      at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
      at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
      at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by rtitle** [comment]
Once this is fixed unignore the test: https://github.com/DataBiosphere/leonardo/pull/210

**Comment by jmthibault79** [comment]
I'm assuming this one will mostly involve adding a `recover` for this error when we delete.
