### ISSUE TITLE
Hail integration is missing dependencies

### ISSUE THREAD

**Issue by rtitle** [DataBiosphere/leonardo#222]
While running through the [Hail tutorial](https://hail.is/docs/stable/tutorials/hail-overview.html), I get the following error:
```
FatalErrorTraceback (most recent call last)
<ipython-input-93-70632a646f56> in <module>()
----> 1 pprint(table.query('SuperPopulation.counter()'))

<decorator-gen-274> in query(self, exprs)

/etc/hail/hail-0.1-5c275cc216e1.zip/hail/java.pyc in handle_py4j(func, *args, **kwargs)
    113 def handle_py4j(func, *args, **kwargs):
    114     try:
--> 115         r = func(*args, **kwargs)
    116     except py4j.protocol.Py4JJavaError as e:
    117         tpl = Env.jutils().handleForPython(e.java_exception)

<decorator-gen-273> in query(self, exprs)

/etc/hail/hail-0.1-5c275cc216e1.zip/hail/typecheck/check.pyc in _typecheck(f, *args, **kwargs)
    243     def _typecheck(f, *args, **kwargs):
    244         check_all(f, args, kwargs, checkers, is_method=True)
--> 245         return f(*args, **kwargs)
    246 
    247     return decorator(_typecheck)

/etc/hail/hail-0.1-5c275cc216e1.zip/hail/keytable.pyc in query(self, exprs)
    860         """
    861 
--> 862         r, t = self.query_typed(exprs)
    863         return r
    864 

<decorator-gen-271> in query_typed(self, exprs)

/etc/hail/hail-0.1-5c275cc216e1.zip/hail/java.pyc in handle_py4j(func, *args, **kwargs)
    119         raise FatalError('%s\n\nJava stack trace:\n%s\n'
    120                          'Hail version: %s\n'
--> 121                          'Error summary: %s' % (deepest, full, Env.hc().version, deepest))
    122     except py4j.protocol.Py4JError as e:
    123         if e.args[0].startswith('An error occurred while calling'):

FatalError: ClassNotFoundException: is.hail.asm4s.AsmFunction2

Java stack trace:
org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 16.0 failed 4 times, most recent failure: Lost task 1.3 in stage 16.0 (TID 108, rt-hail-test-2-m.c.broad-firecloud-dsde.internal): java.lang.NoClassDefFoundError: is/hail/asm4s/AsmFunction2
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at is.hail.asm4s.package$HailClassLoader$.liftedTree1$1(package.scala:254)
	at is.hail.asm4s.package$HailClassLoader$.loadOrDefineClass(package.scala:250)
	at is.hail.asm4s.package$.loadClass(package.scala:261)
	at is.hail.asm4s.FunctionBuilder$$anon$2.apply(FunctionBuilder.scala:218)
	at is.hail.expr.CM$$anonfun$runWithDelayedValues$1.apply(CM.scala:82)
	at is.hail.expr.CM$$anonfun$runWithDelayedValues$1.apply(CM.scala:80)
	at is.hail.expr.AST$$anonfun$runAggregator$1.apply(AST.scala:273)
	at is.hail.expr.AST$$anonfun$runAggregator$1.apply(AST.scala:271)
	at is.hail.methods.Aggregators$$anonfun$10.apply(Aggregators.scala:221)
	at is.hail.methods.Aggregators$$anonfun$10.apply(Aggregators.scala:217)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
	at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.aggregate(TraversableOnce.scala:214)
	at scala.collection.AbstractIterator.aggregate(Iterator.scala:1336)
	at org.apache.spark.rdd.RDD$$anonfun$aggregate$1$$anonfun$22.apply(RDD.scala:1089)
	at org.apache.spark.rdd.RDD$$anonfun$aggregate$1$$anonfun$22.apply(RDD.scala:1089)
	at org.apache.spark.SparkContext$$anonfun$32.apply(SparkContext.scala:1935)
	at org.apache.spark.SparkContext$$anonfun$32.apply(SparkContext.scala:1935)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
	at org.apache.spark.scheduler.Task.run(Task.scala:86)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: is.hail.asm4s.AsmFunction2
	at java.lang.ClassLoader.findClass(ClassLoader.java:530)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 31 more

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1454)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1442)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1441)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1441)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:811)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:811)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:811)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1667)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1622)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1611)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:632)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1873)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1936)
	at org.apache.spark.rdd.RDD$$anonfun$aggregate$1.apply(RDD.scala:1091)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:358)
	at org.apache.spark.rdd.RDD.aggregate(RDD.scala:1084)
	at is.hail.keytable.KeyTable.query(KeyTable.scala:285)
	at is.hail.keytable.KeyTable.query(KeyTable.scala:265)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:237)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)java.lang.NoClassDefFoundError: is/hail/asm4s/AsmFunction2
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at is.hail.asm4s.package$HailClassLoader$.liftedTree1$1(package.scala:254)
	at is.hail.asm4s.package$HailClassLoader$.loadOrDefineClass(package.scala:250)
	at is.hail.asm4s.package$.loadClass(package.scala:261)
	at is.hail.asm4s.FunctionBuilder$$anon$2.apply(FunctionBuilder.scala:218)
	at is.hail.expr.CM$$anonfun$runWithDelayedValues$1.apply(CM.scala:82)
	at is.hail.expr.CM$$anonfun$runWithDelayedValues$1.apply(CM.scala:80)
	at is.hail.expr.AST$$anonfun$runAggregator$1.apply(AST.scala:273)
	at is.hail.expr.AST$$anonfun$runAggregator$1.apply(AST.scala:271)
	at is.hail.methods.Aggregators$$anonfun$10.apply(Aggregators.scala:221)
	at is.hail.methods.Aggregators$$anonfun$10.apply(Aggregators.scala:217)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
	at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.aggregate(TraversableOnce.scala:214)
	at scala.collection.AbstractIterator.aggregate(Iterator.scala:1336)
	at org.apache.spark.rdd.RDD$$anonfun$aggregate$1$$anonfun$22.apply(RDD.scala:1089)
	at org.apache.spark.rdd.RDD$$anonfun$aggregate$1$$anonfun$22.apply(RDD.scala:1089)
	at org.apache.spark.SparkContext$$anonfun$32.apply(SparkContext.scala:1935)
	at org.apache.spark.SparkContext$$anonfun$32.apply(SparkContext.scala:1935)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
	at org.apache.spark.scheduler.Task.run(Task.scala:86)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)java.lang.ClassNotFoundException: is.hail.asm4s.AsmFunction2
	at java.lang.ClassLoader.findClass(ClassLoader.java:530)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at is.hail.asm4s.package$HailClassLoader$.liftedTree1$1(package.scala:254)
	at is.hail.asm4s.package$HailClassLoader$.loadOrDefineClass(package.scala:250)
	at is.hail.asm4s.package$.loadClass(package.scala:261)
	at is.hail.asm4s.FunctionBuilder$$anon$2.apply(FunctionBuilder.scala:218)
	at is.hail.expr.CM$$anonfun$runWithDelayedValues$1.apply(CM.scala:82)
	at is.hail.expr.CM$$anonfun$runWithDelayedValues$1.apply(CM.scala:80)
	at is.hail.expr.AST$$anonfun$runAggregator$1.apply(AST.scala:273)
	at is.hail.expr.AST$$anonfun$runAggregator$1.apply(AST.scala:271)
	at is.hail.methods.Aggregators$$anonfun$10.apply(Aggregators.scala:221)
	at is.hail.methods.Aggregators$$anonfun$10.apply(Aggregators.scala:217)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
	at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.aggregate(TraversableOnce.scala:214)
	at scala.collection.AbstractIterator.aggregate(Iterator.scala:1336)
	at org.apache.spark.rdd.RDD$$anonfun$aggregate$1$$anonfun$22.apply(RDD.scala:1089)
	at org.apache.spark.rdd.RDD$$anonfun$aggregate$1$$anonfun$22.apply(RDD.scala:1089)
	at org.apache.spark.SparkContext$$anonfun$32.apply(SparkContext.scala:1935)
	at org.apache.spark.SparkContext$$anonfun$32.apply(SparkContext.scala:1935)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
	at org.apache.spark.scheduler.Task.run(Task.scala:86)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)



Hail version: 0.1-5c275cc
Error summary: ClassNotFoundException: is.hail.asm4s.AsmFunction2
```

Apparently this has been seen before: http://discuss.hail.is/t/classnotfoundexception-is-hail-asm4s-asmfunction2/231

Something must have broke. Check if we're setting the Spark classpath correctly based on the above post.

**Comment by rtitle** [comment]
Looking at this. I suspect I broke it when refactoring the Dockerfile earlier :(

**Comment by rtitle** [comment]
I think I have fix for this (thanks to Cotton on Hail team)
