### ISSUE TITLE
FC UI auto-test failure: User should be able to create and delete a cluster

### ISSUE THREAD

**Issue by jmthibault79** [DataBiosphere/leonardo#271]
https://fc-jenkins.dsp-techops.broadinstitute.org/job/firecloud-ui-fiab-test-runner/1116/consoleFull:
```
[info] NotebooksSpec:
[info] - User should be able to create and delete a cluster *** FAILED ***
[info]   org.openqa.selenium.TimeoutException: Expected condition failed: waiting for org.broadinstitute.dsde.workbench.service.test.WebBrowserUtil$await$$anon$1@31a29a51 (tried for 900 second(s) with 500 MILLISECONDS interval)
[info] Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T18:33:54.468Z'
[info] System info: host: 'e8a6097c21cd', ip: '172.18.0.6', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-693.11.6.el7.x86_64', java.version: '1.8.0_111-internal'
[info] Driver info: org.openqa.selenium.remote.RemoteWebDriver
[info] Capabilities {acceptSslCerts: true, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.33.506092 (733a02544d189e..., userDataDir: /tmp/.org.chromium.Chromium...}, cssSelectorsEnabled: true, databaseEnabled: false, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 62.0.3202.94, webStorageEnabled: true}
[info] Session ID: 87dfe1d6db722411178a66130cca2288
[info]   at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:82)
[info]   at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:231)
[info]   at org.broadinstitute.dsde.workbench.service.test.WebBrowserUtil$await$.withWaitForCondition(WebBrowserUtil.scala:153)
[info]   at org.broadinstitute.dsde.workbench.service.test.WebBrowserUtil$await$.condition(WebBrowserUtil.scala:52)
[info]   at org.broadinstitute.dsde.firecloud.page.workspaces.notebooks.WorkspaceNotebooksPage.waitUntilClusterIsRunning(WorkspaceNotebooksPage.scala:44)
[info]   at org.broadinstitute.dsde.firecloud.test.notebooks.NotebooksSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$2$$anonfun$apply$3.apply(NotebooksSpec.scala:39)
[info]   at org.broadinstitute.dsde.firecloud.test.notebooks.NotebooksSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$2$$anonfun$apply$3.apply(NotebooksSpec.scala:27)
[info]   at org.broadinstitute.dsde.firecloud.fixture.UserFixtures$class.withSignIn(UserFixtures.scala:79)
[info]   at org.broadinstitute.dsde.firecloud.fixture.UserFixtures$class.withSignIn(UserFixtures.scala:46)
[info]   at org.broadinstitute.dsde.firecloud.fixture.UserFixtures$class.withSignIn(UserFixtures.scala:22)
```

**Comment by jmthibault79** [comment]
Works locally.  Looks like we just got unlucky with a slow cluster creation here.

Improvements under #143 should help here.
