### ISSUE TITLE
The notebooks Dockerfile has stopped working

### ISSUE THREAD

**Issue by jmthibault79** [DataBiosphere/leonardo#324]
As of Tues 17 Apr 2018, it is no longer possible to run `docker build` on the notebooks `Dockerfile`.

One issue is that the specified version of Java is no longer available for download at the Oracle website.  That's an easy fix: #319 

However, that is not sufficient.  More information in the comments.

**Comment by jmthibault79** [comment]
"cannot uninstall pyparsing"
```
Collecting firecloud==0.16.7
  Downloading https://files.pythonhosted.org/packages/df/72/2223d752cfd55af9d273f384bfd4d764b9cfad0cee7fc3720e5030921790/firecloud-0.16.7.tar.gz (42kB)
Requirement already satisfied: google-auth in /usr/local/lib/python2.7/dist-packages (from firecloud==0.16.7) (1.4.1)
Collecting pydot (from firecloud==0.16.7)
  Downloading https://files.pythonhosted.org/packages/c3/f1/e61d6dfe6c1768ed2529761a68f70939e2569da043e9f15a8d84bf56cadf/pydot-1.2.4.tar.gz (132kB)
Requirement already satisfied: requests in /usr/local/lib/python2.7/dist-packages (from firecloud==0.16.7) (2.18.4)
Requirement already satisfied: six in /usr/local/lib/python2.7/dist-packages (from firecloud==0.16.7) (1.11.0)
Collecting pylint==1.7.2 (from firecloud==0.16.7)
  Downloading https://files.pythonhosted.org/packages/4f/9c/a73e0da981a39768cfaff54c0d46588a9284bd25146e24d479aa82c7c7ad/pylint-1.7.2-py2.py3-none-any.whl (644kB)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python2.7/dist-packages (from google-auth->firecloud==0.16.7) (0.2.1)
Requirement already satisfied: cachetools>=2.0.0 in /usr/local/lib/python2.7/dist-packages (from google-auth->firecloud==0.16.7) (2.0.1)
Requirement already satisfied: rsa>=3.1.4 in /usr/local/lib/python2.7/dist-packages (from google-auth->firecloud==0.16.7) (3.4.2)
Collecting pyparsing>=2.1.4 (from pydot->firecloud==0.16.7)
  Downloading https://files.pythonhosted.org/packages/6a/8a/718fd7d3458f9fab8e67186b00abdd345b639976bc7fb3ae722e1b026a50/pyparsing-2.2.0-py2.py3-none-any.whl (56kB)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests->firecloud==0.16.7) (2.6)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests->firecloud==0.16.7) (1.22)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests->firecloud==0.16.7) (2018.4.16)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests->firecloud==0.16.7) (3.0.4)
Collecting mccabe (from pylint==1.7.2->firecloud==0.16.7)
  Downloading https://files.pythonhosted.org/packages/87/89/479dc97e18549e21354893e4ee4ef36db1d237534982482c3681ee6e7b57/mccabe-0.6.1-py2.py3-none-any.whl
Collecting astroid>=1.5.1 (from pylint==1.7.2->firecloud==0.16.7)
  Downloading https://files.pythonhosted.org/packages/f8/59/12a1d965bb99b595bfd72cc9a44863a0c00a2c05c38178f6139285bb00b5/astroid-1.6.3-py2.py3-none-any.whl (289kB)
Requirement already satisfied: singledispatch; python_version < "3.4" in /usr/local/lib/python2.7/dist-packages (from pylint==1.7.2->firecloud==0.16.7) (3.4.0.3)
Requirement already satisfied: configparser; python_version == "2.7" in /usr/local/lib/python2.7/dist-packages (from pylint==1.7.2->firecloud==0.16.7) (3.5.0)
Collecting backports.functools-lru-cache; python_version == "2.7" (from pylint==1.7.2->firecloud==0.16.7)
  Downloading https://files.pythonhosted.org/packages/03/8e/2424c0e65c4a066e28f539364deee49b6451f8fcd4f718fefa50cc3dcf48/backports.functools_lru_cache-1.5-py2.py3-none-any.whl
Collecting isort>=4.2.5 (from pylint==1.7.2->firecloud==0.16.7)
  Downloading https://files.pythonhosted.org/packages/41/d8/a945da414f2adc1d9e2f7d6e7445b27f2be42766879062a2e63616ad4199/isort-4.3.4-py2-none-any.whl (45kB)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.1 in /usr/local/lib/python2.7/dist-packages (from pyasn1-modules>=0.2.1->google-auth->firecloud==0.16.7) (0.4.2)
Requirement already satisfied: enum34>=1.1.3; python_version < "3.4" in /usr/local/lib/python2.7/dist-packages (from astroid>=1.5.1->pylint==1.7.2->firecloud==0.16.7) (1.1.6)
Collecting wrapt (from astroid>=1.5.1->pylint==1.7.2->firecloud==0.16.7)
  Downloading https://files.pythonhosted.org/packages/a0/47/66897906448185fcb77fc3c2b1bc20ed0ecca81a0f2f88eda3fc5a34fc3d/wrapt-1.10.11.tar.gz
Collecting lazy-object-proxy (from astroid>=1.5.1->pylint==1.7.2->firecloud==0.16.7)
  Downloading https://files.pythonhosted.org/packages/52/7e/f0f570ba363e15251bb9fd452257ec2aff91be0187a08a893afbd8ae225f/lazy_object_proxy-1.3.1-cp27-cp27mu-manylinux1_x86_64.whl (56kB)
Requirement already satisfied: futures in /usr/local/lib/python2.7/dist-packages (from isort>=4.2.5->pylint==1.7.2->firecloud==0.16.7) (3.2.0)
Installing collected packages: pyparsing, pydot, mccabe, wrapt, backports.functools-lru-cache, lazy-object-proxy, astroid, isort, pylint, firecloud
  Found existing installation: pyparsing 2.0.3
Cannot uninstall 'pyparsing'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
The command '/bin/sh -c apt-get install -yq --no-install-recommends     python     python-dev     liblzo2-dev     python-matplotlib     python-pandas     python-seaborn     python-tk     python-numpy     liblzo2-dev     libz-dev  && useradd -m -s /bin/bash -N -u $UID $USER  && wget https://bootstrap.pypa.io/get-pip.py  && python get-pip.py  && pip install -U decorator jupyter  && pip install google-cloud  && pip install firecloud==0.16.7  && pip install -U scikit-learn  && pip install ggplot  && pip install bokeh  && pip install pyfasta  && pip install pdoc  && pip install biopython  && pip install bx-python  && pip install fastinterval  && pip install matplotlib-venn' returned a non-zero code: 1
```

**Comment by jmthibault79** [comment]
Solution attempt: explicitly specify an older version of pydot that does not require a newer pyparsing.

Result: works for Python 2 but not Python 3.

**Comment by jmthibault79** [comment]
Solution attempt: install pydot via apt-get instead of pip

Result: docker build completes, but Hail tests fail:
```
     org.scalatest.exceptions.TestFailedException: Some("ImportErrorTraceback (most recent call last)
<ipython-input-1-c9e84bb77056> in <module>()
----> 1 from hail import *

/home/ec2-user/BuildAgent/work/4d93753832b3428a/python/hail/__init__.py in <module>()

/home/ec2-user/BuildAgent/work/4d93753832b3428a/python/hail/expr.py in <module>()

/home/ec2-user/BuildAgent/work/4d93753832b3428a/python/hail/representation/__init__.py in <module>()

/home/ec2-user/BuildAgent/work/4d93753832b3428a/python/hail/representation/variant.py in <module>()

/home/ec2-user/BuildAgent/work/4d93753832b3428a/python/hail/typecheck/__init__.py in <module>()

/home/ec2-user/BuildAgent/work/4d93753832b3428a/python/hail/typecheck/check.py in <module>()

ImportError: cannot import name getargspec") was not equal to None
      at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:340)
      at org.scalatest.Matchers$AnyShouldWrapper.shouldBe(Matchers.scala:6864)
      at org.broadinstitute.dsde.workbench.leonardo.LeonardoTestUtils$class.verifyHailImport(LeonardoTestUtils.scala:408)
      at org.broadinstitute.dsde.workbench.leonardo.ClusterMonitoringSpec.verifyHailImport(ClusterMonitoringSpec.scala:13)
```

**Comment by jmthibault79** [comment]
Solution attempt: install many python packages via apt-get instead of pip

Result: same as above

**Comment by rtitle** [comment]
Idea: maybe this is due to a pip version change. Here is an old build:

https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-build/1930/consoleFull
```
Downloading pip-9.0.3-py2.py3-none-any.whl (1.4MB)
// later...
DEPRECATION: Uninstalling a distutils installed project (pyparsing) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
```

Here is a recent build:

https://fc-jenkins.dsp-techops.broadinstitute.org/job/leonardo-build/1965/consoleFull
```
Collecting pip
  Downloading https://files.pythonhosted.org/packages/62/a1/0d452b6901b0157a0134fd27ba89bf95a857fbda64ba52e1ca2cf61d8412/pip-10.0.0-py2.py3-none-any.whl (1.3MB)
// later...
Cannot uninstall 'pyparsing'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

I'm going to see if we can continue to use pip 9 for the time being.

**Comment by rtitle** [comment]
Actually I take that back. This seems to make the docker build work locally -- seeing if it also passes tests: https://github.com/DataBiosphere/leonardo/pull/325/
