### ISSUE TITLE
Errors when Google and Leo are out of sync

### ISSUE THREAD

**Issue by rtitle** [DataBiosphere/leonardo#494]
For example, we currently are logging the following errors for auto-freezing clusters made in free-trial projects:
```
[WARN] [18:39:22.443] [leonardo-akka.actor.default-dispatcher-2] o.b.d.w.l.m.ClusterMonitorSupervisor - Error occurred auto freezing cluster fccredits-iodine-puce-4025/test
org.broadinstitute.dsde.workbench.model.WorkbenchException: Call to Google API failed for fccredits-iodine-puce-4025 / test-m. Status: 403. Message: Project fccredits-iodine-puce-4025 cannot accept requests to setMetadata while in an inactive billing state.  Billing state may take several minutes to update.
	at org.broadinstitute.dsde.workbench.leonardo.dao.google.HttpGoogleComputeDAO$GoogleExceptionSupport$$anonfun$handleGoogleException$1.applyOrElse(HttpGoogleComputeDAO.scala:179)
	at org.broadinstitute.dsde.workbench.leonardo.dao.google.HttpGoogleComputeDAO$GoogleExceptionSupport$$anonfun$handleGoogleException$1.applyOrElse(HttpGoogleComputeDAO.scala:175)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
	at scala.util.Failure.recover(Try.scala:230)
	at scala.concurrent.Future.$anonfun$recover$1(Future.scala:391)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
{
  "code" : 403,
  "errors" : [ {
    "domain" : "global",
    "message" : "Project fccredits-iodine-puce-4025 cannot accept requests to setMetadata while in an inactive billing state.  Billing state may take several minutes to update.",
    "reason" : "inactiveBillingState"
  } ],
  "message" : "Project fccredits-iodine-puce-4025 cannot accept requests to setMetadata while in an inactive billing state.  Billing state may take several minutes to update."
}
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1065)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
	at org.broadinstitute.dsde.workbench.google.GoogleUtilities.$anonfun$executeGoogleCall$1(GoogleUtilities.scala:70)
	at scala.util.Try$.apply(Try.scala:209)
	at org.broadinstitute.dsde.workbench.google.GoogleUtilities.executeGoogleCall(GoogleUtilities.scala:70)
	at org.broadinstitute.dsde.workbench.google.GoogleUtilities.executeGoogleCall$(GoogleUtilities.scala:67)
	at org.broadinstitute.dsde.workbench.google.AbstractHttpGoogleDAO.executeGoogleCall(AbstractHttpGoogleDAO.scala:14)
	at org.broadinstitute.dsde.workbench.google.GoogleUtilities.executeGoogleRequest(GoogleUtilities.scala:51)
	at org.broadinstitute.dsde.workbench.google.GoogleUtilities.executeGoogleRequest$(GoogleUtilities.scala:50)
	at org.broadinstitute.dsde.workbench.google.AbstractHttpGoogleDAO.executeGoogleRequest(AbstractHttpGoogleDAO.scala:14)
	at org.broadinstitute.dsde.workbench.leonardo.dao.google.HttpGoogleComputeDAO.$anonfun$addInstanceMetadata$11(HttpGoogleComputeDAO.scala:99)
	at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread$$anon$3.block(ThreadPoolBuilder.scala:167)
	at akka.dispatch.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:3641)
	at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread.blockOn(ThreadPoolBuilder.scala:165)
	at akka.dispatch.BatchingExecutor$BlockableBatch.blockOn(BatchingExecutor.scala:106)
	at scala.concurrent.package$.blocking(package.scala:142)
	at org.broadinstitute.dsde.workbench.google.GoogleUtilities.$anonfun$retryWhen500orGoogleError$3(GoogleUtilities.scala:42)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:654)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
	... 14 common frames omitted
```
It looks like a free-trial project's cluster is being auto-paused, after the free trial is ended. We should probably detect this and ignore these types of clusters.

**Comment by rtitle** [comment]
Look at making this more general -- it's possible for clusters to be deleted in Google for reasons other than free trial. We should handle this case in general.

**Comment by vkumra-broad** [comment]
tech doc for fix

https://docs.google.com/document/d/1VCSzsiB5-tUkVwmgE_I9XwgAC_lMCXm79Hm70FLnX5Y/edit#
