### ISSUE TITLE
Allow Bigquerying from command line with SSL validation

### ISSUE THREAD

**Issue by akarukappadath** [DataBiosphere/leonardo#673]
With the recent slew of upgrades to the dockerfile (aka the DockerFire), users are no longer able to run bigquery commands from the command line without using the flag `--disable_ssl_validation`, or else they see: 

```BigQuery error in query operation: Cannot contact server. Please try again.
Traceback: Traceback (most recent call last):
File "/usr/lib/google-cloud-sdk/platform/bq/bigquery_client.py", line 886, in BuildApiClient
response_metadata, discovery_document = http.request(discovery_url)
File "/usr/lib/google-cloud-sdk/platform/bq/third_party/oauth2client_4_0/transport.py", line 176, in new_request
redirections, connection_type)
File "/usr/lib/google-cloud-sdk/platform/bq/third_party/oauth2client_4_0/transport.py", line 283, in request
connection_type=connection_type)
File "/usr/lib/google-cloud-sdk/platform/bq/third_party/httplib2/__init__.py", line 1626, in request
(response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
File "/usr/lib/google-cloud-sdk/platform/bq/third_party/httplib2/__init__.py", line 1368, in _request
(response, content) = self._conn_request(conn, request_uri, method, body, headers)
File "/usr/lib/google-cloud-sdk/platform/bq/third_party/httplib2/__init__.py", line 1288, in _conn_request
conn.connect()
File "/usr/lib/google-cloud-sdk/platform/bq/third_party/httplib2/__init__.py", line 1082, in connect
raise SSLHandshakeError(e)
SSLHandshakeError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)```

**Comment by deflaux** [comment]
+1, it would be great to get this fixed

**Comment by sharmatime** [comment]
Google hasn't made a fix yet - Matt's checking on any possible security implications

**Comment by sharmatime** [comment]
Is this still an issue?

**Comment by deflaux** [comment]
I checked recently and it appears to be fixed!

**Comment by MatthewBemis** [comment]
Closed because it has been reported as fixed!
